name: Running Java Interview programs

on: [push, pull_request]
  branches: ["main"]

jobs:
  test:
    steps:
      - name: SETUP JAVA 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: |
          java FilterNCollect.java
