name: Running Java Interview programs

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: SETUP JAVA 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'
      - run: |
          mvn clean verify
